<?php

if (!defined('ABSPATH')) exit;

class gdcet_meta_predefined_data {
    public $_numeric_arrays = array(
        'wordpress_major', 
        'wordpress_minor',
        'php_major'
    );

    public $_data_wordpress_major = array(
        '0.7', 
        '1.0', 
        '1.2', 
        '1.5', 
        '2.0', 
        '2.1', 
        '2.2', 
        '2.3', 
        '2.5', 
        '2.6', 
        '2.7', 
        '2.8', 
        '2.9', 
        '3.0', 
        '3.1', 
        '3.2', 
        '3.3', 
        '3.4', 
        '3.5', 
        '3.6', 
        '3.7', 
        '3.8', 
        '3.9', 
        '4.0', 
        '4.1', 
        '4.2', 
        '4.3', 
        '4.4', 
        '4.5', 
        '4.6', 
        '4.7', 
        '4.8',
        '4.9',
        '5.0',
        '5.1',
        '5.2',
        '5.3'
    );

    public $_data_wordpress_minor = array(
        '0.70', 
        '0.71', 
        '0.711', 
        '0.72', 
        '1.0', 
        '1.0.1', 
        '1.0.2', 
        '1.2', 
        '1.2.1', 
        '1.2.2', 
        '1.5', 
        '1.5.1', 
        '1.5.1.1', 
        '1.5.1.2', 
        '1.5.1.3', 
        '1.5.2', 
        '2.0', 
        '2.0.1', 
        '2.0.2', 
        '2.0.3', 
        '2.0.4', 
        '2.0.5', 
        '2.0.6', 
        '2.0.7', 
        '2.0.8', 
        '2.0.9', 
        '2.0.10', 
        '2.0.11', 
        '2.1', 
        '2.1.1', 
        '2.1.2', 
        '2.1.3', 
        '2.2', 
        '2.2.1', 
        '2.2.2', 
        '2.2.3', 
        '2.3', 
        '2.3.1', 
        '2.3.2', 
        '2.3.3', 
        '2.5', 
        '2.5.1', 
        '2.6', 
        '2.6.1', 
        '2.6.2', 
        '2.6.3', 
        '2.6.5', 
        '2.7', 
        '2.7.1', 
        '2.8', 
        '2.8.1', 
        '2.8.2', 
        '2.8.3', 
        '2.8.4', 
        '2.8.5', 
        '2.8.6', 
        '2.9', 
        '2.9.1', 
        '2.9.2', 
        '3.0', 
        '3.0.1', 
        '3.0.2', 
        '3.0.3', 
        '3.0.4', 
        '3.0.5', 
        '3.0.6', 
        '3.1', 
        '3.1.1', 
        '3.1.2', 
        '3.1.3', 
        '3.1.4', 
        '3.2', 
        '3.2.1', 
        '3.3', 
        '3.3.1', 
        '3.3.2', 
        '3.3.3', 
        '3.4', 
        '3.4.1', 
        '3.4.2', 
        '3.5', 
        '3.5.1', 
        '3.5.2', 
        '3.6', 
        '3.6.1', 
        '3.7', 
        '3.7.1', 
        '3.7.2', 
        '3.7.3', 
        '3.7.4', 
        '3.7.5', 
        '3.7.6', 
        '3.7.7', 
        '3.7.8', 
        '3.7.9', 
        '3.7.10', 
        '3.7.11', 
        '3.7.12', 
        '3.7.13', 
        '3.7.14', 
        '3.7.15', 
        '3.7.16', 
        '3.7.17', 
        '3.7.18', 
        '3.7.19', 
        '3.7.20', 
        '3.7.21', 
        '3.7.22', 
        '3.7.23', 
        '3.7.24', 
        '3.7.25', 
        '3.7.26', 
        '3.7.27', 
        '3.7.28',
        '3.7.29',
        '3.7.30',
        '3.7.31',
        '3.7.32',
        '3.8',
        '3.8.1', 
        '3.8.2', 
        '3.8.3', 
        '3.8.4', 
        '3.8.5', 
        '3.8.6', 
        '3.8.7', 
        '3.8.8', 
        '3.8.9', 
        '3.8.10', 
        '3.8.11', 
        '3.8.12', 
        '3.8.13', 
        '3.8.14', 
        '3.8.15', 
        '3.8.16', 
        '3.8.17', 
        '3.8.18', 
        '3.8.19', 
        '3.8.20', 
        '3.8.21', 
        '3.8.22', 
        '3.8.23', 
        '3.8.24', 
        '3.8.25', 
        '3.8.26', 
        '3.8.27', 
        '3.8.28',
        '3.8.29',
        '3.8.30',
        '3.8.31',
        '3.8.32',
        '3.9', 
        '3.9.1', 
        '3.9.2', 
        '3.9.3', 
        '3.9.4', 
        '3.9.5', 
        '3.9.6', 
        '3.9.7', 
        '3.9.8', 
        '3.9.9', 
        '3.9.10', 
        '3.9.11', 
        '3.9.12', 
        '3.9.13', 
        '3.9.14', 
        '3.9.15', 
        '3.9.16', 
        '3.9.17', 
        '3.9.18', 
        '3.9.19', 
        '3.9.20', 
        '3.9.21', 
        '3.9.22', 
        '3.9.23', 
        '3.9.24', 
        '3.9.25', 
        '3.9.26',
        '3.9.27',
        '3.9.28',
        '3.9.29',
        '3.9.30',
        '4.0',
        '4.0.1', 
        '4.0.2', 
        '4.0.3', 
        '4.0.4', 
        '4.0.5', 
        '4.0.6', 
        '4.0.7', 
        '4.0.8', 
        '4.0.9', 
        '4.0.10', 
        '4.0.11', 
        '4.0.12', 
        '4.0.13', 
        '4.0.14', 
        '4.0.15', 
        '4.0.16', 
        '4.0.17', 
        '4.0.18', 
        '4.0.19', 
        '4.0.20', 
        '4.0.21', 
        '4.0.22', 
        '4.0.23', 
        '4.0.24', 
        '4.0.25',
        '4.0.26',
        '4.0.27',
        '4.0.28',
        '4.0.29',
        '4.1',
        '4.1.1', 
        '4.1.2', 
        '4.1.3', 
        '4.1.4', 
        '4.1.5', 
        '4.1.6', 
        '4.1.7', 
        '4.1.8', 
        '4.1.9', 
        '4.1.10', 
        '4.1.11', 
        '4.1.12', 
        '4.1.13', 
        '4.1.14', 
        '4.1.15', 
        '4.1.16', 
        '4.1.17', 
        '4.1.18', 
        '4.1.19', 
        '4.1.20', 
        '4.1.21', 
        '4.1.22', 
        '4.1.23', 
        '4.1.24', 
        '4.1.25',
        '4.1.26',
        '4.1.27',
        '4.1.28',
        '4.1.29',
        '4.2',
        '4.2.1', 
        '4.2.2', 
        '4.2.3', 
        '4.2.4', 
        '4.2.5', 
        '4.2.6', 
        '4.2.7', 
        '4.2.8', 
        '4.2.9', 
        '4.2.10', 
        '4.2.11', 
        '4.2.12', 
        '4.2.13', 
        '4.2.14', 
        '4.2.15', 
        '4.2.16', 
        '4.2.17', 
        '4.2.18', 
        '4.2.19', 
        '4.2.20', 
        '4.2.21', 
        '4.2.22',
        '4.2.23',
        '4.2.24',
        '4.2.25',
        '4.2.26',
        '4.3',
        '4.3.1', 
        '4.3.2', 
        '4.3.3', 
        '4.3.4', 
        '4.3.5', 
        '4.3.6', 
        '4.3.7', 
        '4.3.8', 
        '4.3.9', 
        '4.3.10', 
        '4.3.11', 
        '4.3.12', 
        '4.3.13', 
        '4.3.14', 
        '4.3.15', 
        '4.3.16', 
        '4.3.17', 
        '4.3.18',
        '4.3.19',
        '4.3.20',
        '4.3.21',
        '4.3.22',
        '4.4',
        '4.4.1', 
        '4.4.2', 
        '4.4.3', 
        '4.4.4', 
        '4.4.5', 
        '4.4.6', 
        '4.4.7', 
        '4.4.8', 
        '4.4.9', 
        '4.4.10', 
        '4.4.11', 
        '4.4.12', 
        '4.4.13', 
        '4.4.14', 
        '4.4.15', 
        '4.4.16', 
        '4.4.17',
        '4.4.18',
        '4.4.19',
        '4.4.20',
        '4.4.21',
        '4.5',
        '4.5.1', 
        '4.5.2', 
        '4.5.3', 
        '4.5.4', 
        '4.5.5', 
        '4.5.6', 
        '4.5.7', 
        '4.5.8', 
        '4.5.9', 
        '4.5.10', 
        '4.5.11', 
        '4.5.12', 
        '4.5.13', 
        '4.5.14', 
        '4.5.15', 
        '4.5.16',
        '4.5.17',
        '4.5.18',
        '4.5.19',
        '4.5.20',
        '4.6',
        '4.6.1', 
        '4.6.2', 
        '4.6.3', 
        '4.6.4', 
        '4.6.5', 
        '4.6.6', 
        '4.6.7', 
        '4.6.8', 
        '4.6.9', 
        '4.6.10', 
        '4.6.11', 
        '4.6.12', 
        '4.6.13',
        '4.6.14',
        '4.6.15',
        '4.6.16',
        '4.6.17',
        '4.7',
        '4.7.1', 
        '4.7.2', 
        '4.7.3', 
        '4.7.4', 
        '4.7.5', 
        '4.7.6', 
        '4.7.7', 
        '4.7.8', 
        '4.7.9', 
        '4.7.10', 
        '4.7.11', 
        '4.7.12',
        '4.7.13',
        '4.7.14',
        '4.7.15',
        '4.7.16',
        '4.8',
        '4.8.1',
        '4.8.2',
        '4.8.3',
        '4.8.4',
        '4.8.5',
        '4.8.6',
        '4.8.7',
        '4.8.8',
        '4.8.9',
        '4.8.10',
        '4.8.11',
        '4.8.12',
        '4.9',
        '4.9.1', 
        '4.9.2', 
        '4.9.3',
        '4.9.4',
        '4.9.5',
        '4.9.6',
        '4.9.7',
        '4.9.8',
        '4.9.9',
        '4.9.10',
        '4.9.11',
        '4.9.12',
        '4.9.13',
        '5.0',
        '5.0.1',
        '5.0.2',
        '5.0.3',
        '5.0.4',
        '5.0.6',
        '5.0.7',
        '5.0.8',
        '5.1',
        '5.1.1',
        '5.1.2',
        '5.1.3',
        '5.1.4',
        '5.2',
        '5.2.1',
        '5.2.2',
        '5.2.3',
        '5.2.4',
        '5.2.5',
        '5.3',
        '5.3.1',
        '5.3.2'
    );

    public $_data_php_major = array(
        '1.0',
        '2.0',
        '3.0',
        '4.0',
        '4.1',
        '4.2',
        '4.3',
        '4.4',
        '5.0',
        '5.1',
        '5.2',
        '5.3',
        '5.4',
        '5.5',
        '5.6',
        '7.0',
        '7.1',
        '7.2',
        '7.3',
        '7.4'
    );

    public $_data_countries = array(
        'AF' => 'Afghanistan',
        'AX' => 'Åland Islands',
        'AL' => 'Albania',
        'DZ' => 'Algeria',
        'AS' => 'American Samoa',
        'AD' => 'Andorra',
        'AO' => 'Angola',
        'AI' => 'Anguilla',
        'AQ' => 'Antarctica',
        'AG' => 'Antigua & Barbuda',
        'AR' => 'Argentina',
        'AM' => 'Armenia',
        'AW' => 'Aruba',
        'AC' => 'Ascension Island',
        'AU' => 'Australia',
        'AT' => 'Austria',
        'AZ' => 'Azerbaijan',
        'BS' => 'Bahamas',
        'BH' => 'Bahrain',
        'BD' => 'Bangladesh',
        'BB' => 'Barbados',
        'BY' => 'Belarus',
        'BE' => 'Belgium',
        'BZ' => 'Belize',
        'BJ' => 'Benin',
        'BM' => 'Bermuda',
        'BT' => 'Bhutan',
        'BO' => 'Bolivia',
        'BA' => 'Bosnia & Herzegovina',
        'BW' => 'Botswana',
        'BR' => 'Brazil',
        'IO' => 'British Indian Ocean Territory',
        'VG' => 'British Virgin Islands',
        'BN' => 'Brunei',
        'BG' => 'Bulgaria',
        'BF' => 'Burkina Faso',
        'BI' => 'Burundi',
        'KH' => 'Cambodia',
        'CM' => 'Cameroon',
        'CA' => 'Canada',
        'IC' => 'Canary Islands',
        'CV' => 'Cape Verde',
        'BQ' => 'Caribbean Netherlands',
        'KY' => 'Cayman Islands',
        'CF' => 'Central African Republic',
        'EA' => 'Ceuta & Melilla',
        'TD' => 'Chad',
        'CL' => 'Chile',
        'CN' => 'China',
        'CX' => 'Christmas Island',
        'CC' => 'Cocos (Keeling) Islands',
        'CO' => 'Colombia',
        'KM' => 'Comoros',
        'CG' => 'Congo - Brazzaville',
        'CD' => 'Congo - Kinshasa',
        'CK' => 'Cook Islands',
        'CR' => 'Costa Rica',
        'CI' => 'Côte d’Ivoire',
        'HR' => 'Croatia',
        'CU' => 'Cuba',
        'CW' => 'Curaçao',
        'CY' => 'Cyprus',
        'CZ' => 'Czech Republic',
        'DK' => 'Denmark',
        'DG' => 'Diego Garcia',
        'DJ' => 'Djibouti',
        'DM' => 'Dominica',
        'DO' => 'Dominican Republic',
        'EC' => 'Ecuador',
        'EG' => 'Egypt',
        'SV' => 'El Salvador',
        'GQ' => 'Equatorial Guinea',
        'ER' => 'Eritrea',
        'EE' => 'Estonia',
        'ET' => 'Ethiopia',
        'FK' => 'Falkland Islands',
        'FO' => 'Faroe Islands',
        'FJ' => 'Fiji',
        'FI' => 'Finland',
        'FR' => 'France',
        'GF' => 'French Guiana',
        'PF' => 'French Polynesia',
        'TF' => 'French Southern Territories',
        'GA' => 'Gabon',
        'GM' => 'Gambia',
        'GE' => 'Georgia',
        'DE' => 'Germany',
        'GH' => 'Ghana',
        'GI' => 'Gibraltar',
        'GR' => 'Greece',
        'GL' => 'Greenland',
        'GD' => 'Grenada',
        'GP' => 'Guadeloupe',
        'GU' => 'Guam',
        'GT' => 'Guatemala',
        'GG' => 'Guernsey',
        'GN' => 'Guinea',
        'GW' => 'Guinea-Bissau',
        'GY' => 'Guyana',
        'HT' => 'Haiti',
        'HN' => 'Honduras',
        'HK' => 'Hong Kong SAR China',
        'HU' => 'Hungary',
        'IS' => 'Iceland',
        'IN' => 'India',
        'ID' => 'Indonesia',
        'IR' => 'Iran',
        'IQ' => 'Iraq',
        'IE' => 'Ireland',
        'IM' => 'Isle of Man',
        'IL' => 'Israel',
        'IT' => 'Italy',
        'JM' => 'Jamaica',
        'JP' => 'Japan',
        'JE' => 'Jersey',
        'JO' => 'Jordan',
        'KZ' => 'Kazakhstan',
        'KE' => 'Kenya',
        'KI' => 'Kiribati',
        'KW' => 'Kuwait',
        'KG' => 'Kyrgyzstan',
        'LA' => 'Laos',
        'LV' => 'Latvia',
        'LB' => 'Lebanon',
        'LS' => 'Lesotho',
        'LR' => 'Liberia',
        'LY' => 'Libya',
        'LI' => 'Liechtenstein',
        'LT' => 'Lithuania',
        'LU' => 'Luxembourg',
        'MO' => 'Macau SAR China',
        'MK' => 'Macedonia',
        'MG' => 'Madagascar',
        'MW' => 'Malawi',
        'MY' => 'Malaysia',
        'MV' => 'Maldives',
        'ML' => 'Mali',
        'MT' => 'Malta',
        'MH' => 'Marshall Islands',
        'MQ' => 'Martinique',
        'MR' => 'Mauritania',
        'MU' => 'Mauritius',
        'YT' => 'Mayotte',
        'MX' => 'Mexico',
        'FM' => 'Micronesia',
        'MD' => 'Moldova',
        'MC' => 'Monaco',
        'MN' => 'Mongolia',
        'ME' => 'Montenegro',
        'MS' => 'Montserrat',
        'MA' => 'Morocco',
        'MZ' => 'Mozambique',
        'MM' => 'Myanmar (Burma)',
        'NA' => 'Namibia',
        'NR' => 'Nauru',
        'NP' => 'Nepal',
        'NL' => 'Netherlands',
        'NC' => 'New Caledonia',
        'NZ' => 'New Zealand',
        'NI' => 'Nicaragua',
        'NE' => 'Niger',
        'NG' => 'Nigeria',
        'NU' => 'Niue',
        'NF' => 'Norfolk Island',
        'KP' => 'North Korea',
        'MP' => 'Northern Mariana Islands',
        'NO' => 'Norway',
        'OM' => 'Oman',
        'PK' => 'Pakistan',
        'PW' => 'Palau',
        'PS' => 'Palestinian Territories',
        'PA' => 'Panama',
        'PG' => 'Papua New Guinea',
        'PY' => 'Paraguay',
        'PE' => 'Peru',
        'PH' => 'Philippines',
        'PN' => 'Pitcairn Islands',
        'PL' => 'Poland',
        'PT' => 'Portugal',
        'PR' => 'Puerto Rico',
        'QA' => 'Qatar',
        'RE' => 'Réunion',
        'RO' => 'Romania',
        'RU' => 'Russia',
        'RW' => 'Rwanda',
        'WS' => 'Samoa',
        'SM' => 'San Marino',
        'ST' => 'São Tomé & Príncipe',
        'SA' => 'Saudi Arabia',
        'SN' => 'Senegal',
        'RS' => 'Serbia',
        'SC' => 'Seychelles',
        'SL' => 'Sierra Leone',
        'SG' => 'Singapore',
        'SX' => 'Sint Maarten',
        'SK' => 'Slovakia',
        'SI' => 'Slovenia',
        'SB' => 'Solomon Islands',
        'SO' => 'Somalia',
        'ZA' => 'South Africa',
        'GS' => 'South Georgia & South Sandwich Islands',
        'KR' => 'South Korea',
        'SS' => 'South Sudan',
        'ES' => 'Spain',
        'LK' => 'Sri Lanka',
        'BL' => 'St. Barthélemy',
        'SH' => 'St. Helena',
        'KN' => 'St. Kitts & Nevis',
        'LC' => 'St. Lucia',
        'MF' => 'St. Martin',
        'PM' => 'St. Pierre & Miquelon',
        'VC' => 'St. Vincent & Grenadines',
        'SD' => 'Sudan',
        'SR' => 'Suriname',
        'SJ' => 'Svalbard & Jan Mayen',
        'SZ' => 'Swaziland',
        'SE' => 'Sweden',
        'CH' => 'Switzerland',
        'SY' => 'Syria',
        'TW' => 'Taiwan',
        'TJ' => 'Tajikistan',
        'TZ' => 'Tanzania',
        'TH' => 'Thailand',
        'TL' => 'Timor-Leste',
        'TG' => 'Togo',
        'TK' => 'Tokelau',
        'TO' => 'Tonga',
        'TT' => 'Trinidad & Tobago',
        'TA' => 'Tristan da Cunha',
        'TN' => 'Tunisia',
        'TR' => 'Turkey',
        'TM' => 'Turkmenistan',
        'TC' => 'Turks & Caicos Islands',
        'TV' => 'Tuvalu',
        'UM' => 'U.S. Outlying Islands',
        'VI' => 'U.S. Virgin Islands',
        'UG' => 'Uganda',
        'UA' => 'Ukraine',
        'AE' => 'United Arab Emirates',
        'GB' => 'United Kingdom',
        'US' => 'United States',
        'UY' => 'Uruguay',
        'UZ' => 'Uzbekistan',
        'VU' => 'Vanuatu',
        'VA' => 'Vatican City',
        'VE' => 'Venezuela',
        'VN' => 'Vietnam',
        'WF' => 'Wallis & Futuna',
        'EH' => 'Western Sahara',
        'YE' => 'Yemen',
        'ZM' => 'Zambia',
        'ZW' => 'Zimbabwe'
    );

    public $_data_us_states = array(
        'AL' => 'Alabama',
        'AK' => 'Alaska',
        'AZ' => 'Arizona',
        'AR' => 'Arkansas',
        'CA' => 'California',
        'CO' => 'Colorado',
        'CT' => 'Connecticut',
        'DE' => 'Delaware',
        'DC' => 'District of Columbia',
        'FL' => 'Florida',
        'GA' => 'Georgia',
        'HI' => 'Hawaii',
        'ID' => 'Idaho',
        'IL' => 'Illinois',
        'IN' => 'Indiana',
        'IA' => 'Iowa',
        'KS' => 'Kansas',
        'KY' => 'Kentucky',
        'LA' => 'Louisiana',
        'ME' => 'Maine',
        'MD' => 'Maryland',
        'MA' => 'Massachusetts',
        'MI' => 'Michigan',
        'MN' => 'Minnesota',
        'MS' => 'Mississippi',
        'MO' => 'Missouri',
        'MT' => 'Montana',
        'NE' => 'Nebraska',
        'NV' => 'Nevada',
        'NH' => 'New Hampshire',
        'NJ' => 'New Jersey',
        'NM' => 'New Mexico',
        'NY' => 'New York',
        'NC' => 'North Carolina',
        'ND' => 'North Dakota',
        'OH' => 'Ohio',
        'OK' => 'Oklahoma',
        'OR' => 'Oregon',
        'PA' => 'Pennsylvania',
        'RI' => 'Rhode Island',
        'SC' => 'South Carolina',
        'SD' => 'South Dakota',
        'TN' => 'Tennessee',
        'TX' => 'Texas',
        'UT' => 'Utah',
        'VT' => 'Vermont',
        'VA' => 'Virginia',
        'WA' => 'Washington',
        'WV' => 'West Virginia',
        'WI' => 'Wisconsin',
        'WY' => 'Wyoming'
    );

    public $_data_canada_states = array(
        'BC' => 'British Columbia', 
        'ON' => 'Ontario', 
        'NL' => 'Newfoundland and Labrador', 
        'NS' => 'Nova Scotia', 
        'PE' => 'Prince Edward Island', 
        'NB' => 'New Brunswick', 
        'QC' => 'Quebec', 
        'MB' => 'Manitoba', 
        'SK' => 'Saskatchewan', 
        'AB' => 'Alberta', 
        'NT' => 'Northwest Territories', 
        'NU' => 'Nunavut',
        'YT' => 'Yukon Territory'
    );

    public $_data_languages = array(
        'ab' => 'Abkhazian',
        'ace' => 'Achinese',
        'ach' => 'Acoli',
        'ada' => 'Adangme',
        'ady' => 'Adyghe',
        'aa' => 'Afar',
        'afh' => 'Afrihili',
        'af' => 'Afrikaans',
        'agq' => 'Aghem',
        'ain' => 'Ainu',
        'ak' => 'Akan',
        'akk' => 'Akkadian',
        'bss' => 'Akoose',
        'akz' => 'Alabama',
        'sq' => 'Albanian',
        'ale' => 'Aleut',
        'arq' => 'Algerian Arabic',
        'en_US' => 'American English',
        'ase' => 'American Sign Language',
        'am' => 'Amharic',
        'egy' => 'Ancient Egyptian',
        'grc' => 'Ancient Greek',
        'anp' => 'Angika',
        'njo' => 'Ao Naga',
        'ar' => 'Arabic',
        'an' => 'Aragonese',
        'arc' => 'Aramaic',
        'aro' => 'Araona',
        'arp' => 'Arapaho',
        'arw' => 'Arawak',
        'hy' => 'Armenian',
        'rup' => 'Aromanian',
        'frp' => 'Arpitan',
        'as' => 'Assamese',
        'ast' => 'Asturian',
        'asa' => 'Asu',
        'cch' => 'Atsam',
        'en_AU' => 'Australian English',
        'de_AT' => 'Austrian German',
        'av' => 'Avaric',
        'ae' => 'Avestan',
        'awa' => 'Awadhi',
        'ay' => 'Aymara',
        'az' => 'Azerbaijani',
        'bfq' => 'Badaga',
        'ksf' => 'Bafia',
        'bfd' => 'Bafut',
        'bqi' => 'Bakhtiari',
        'ban' => 'Balinese',
        'bal' => 'Baluchi',
        'bm' => 'Bambara',
        'bax' => 'Bamun',
        'bjn' => 'Banjar',
        'bas' => 'Basaa',
        'ba' => 'Bashkir',
        'eu' => 'Basque',
        'bbc' => 'Batak Toba',
        'bar' => 'Bavarian',
        'bej' => 'Beja',
        'be' => 'Belarusian',
        'bem' => 'Bemba',
        'bez' => 'Bena',
        'bn' => 'Bengali',
        'bew' => 'Betawi',
        'bho' => 'Bhojpuri',
        'bik' => 'Bikol',
        'bin' => 'Bini',
        'bpy' => 'Bishnupriya',
        'bi' => 'Bislama',
        'byn' => 'Blin',
        'zbl' => 'Blissymbols',
        'brx' => 'Bodo',
        'bs' => 'Bosnian',
        'brh' => 'Brahui',
        'bra' => 'Braj',
        'pt_BR' => 'Brazilian Portuguese',
        'br' => 'Breton',
        'en_GB' => 'British English',
        'bug' => 'Buginese',
        'bg' => 'Bulgarian',
        'bum' => 'Bulu',
        'bua' => 'Buriat',
        'my' => 'Burmese',
        'cad' => 'Caddo',
        'frc' => 'Cajun French',
        'en_CA' => 'Canadian English',
        'fr_CA' => 'Canadian French',
        'yue' => 'Cantonese',
        'cps' => 'Capiznon',
        'car' => 'Carib',
        'ca' => 'Catalan',
        'cay' => 'Cayuga',
        'ceb' => 'Cebuano',
        'tzm' => 'Central Atlas Tamazight',
        'dtp' => 'Central Dusun',
        'ckb' => 'Central Kurdish',
        'esu' => 'Central Yupik',
        'shu' => 'Chadian Arabic',
        'chg' => 'Chagatai',
        'ch' => 'Chamorro',
        'ce' => 'Chechen',
        'chr' => 'Cherokee',
        'chy' => 'Cheyenne',
        'chb' => 'Chibcha',
        'cgg' => 'Chiga',
        'qug' => 'Chimborazo Highland Quichua',
        'zh' => 'Chinese',
        'chn' => 'Chinook Jargon',
        'chp' => 'Chipewyan',
        'cho' => 'Choctaw',
        'cu' => 'Church Slavic',
        'chk' => 'Chuukese',
        'cv' => 'Chuvash',
        'nwc' => 'Classical Newari',
        'syc' => 'Classical Syriac',
        'ksh' => 'Colognian',
        'swb' => 'Comorian',
        'swc' => 'Congo Swahili',
        'cop' => 'Coptic',
        'kw' => 'Cornish',
        'co' => 'Corsican',
        'cr' => 'Cree',
        'mus' => 'Creek',
        'crh' => 'Crimean Turkish',
        'hr' => 'Croatian',
        'cs' => 'Czech',
        'dak' => 'Dakota',
        'da' => 'Danish',
        'dar' => 'Dargwa',
        'dzg' => 'Dazaga',
        'del' => 'Delaware',
        'din' => 'Dinka',
        'dv' => 'Divehi',
        'doi' => 'Dogri',
        'dgr' => 'Dogrib',
        'dua' => 'Duala',
        'nl' => 'Dutch',
        'dyu' => 'Dyula',
        'dz' => 'Dzongkha',
        'frs' => 'Eastern Frisian',
        'efi' => 'Efik',
        'arz' => 'Egyptian Arabic',
        'eka' => 'Ekajuk',
        'elx' => 'Elamite',
        'ebu' => 'Embu',
        'egl' => 'Emilian',
        'en' => 'English',
        'myv' => 'Erzya',
        'eo' => 'Esperanto',
        'et' => 'Estonian',
        'pt_PT' => 'European Portuguese',
        'es_ES' => 'European Spanish',
        'ee' => 'Ewe',
        'ewo' => 'Ewondo',
        'ext' => 'Extremaduran',
        'fan' => 'Fang',
        'fat' => 'Fanti',
        'fo' => 'Faroese',
        'hif' => 'Fiji Hindi',
        'fj' => 'Fijian',
        'fil' => 'Filipino',
        'fi' => 'Finnish',
        'nl_BE' => 'Flemish',
        'fon' => 'Fon',
        'gur' => 'Frafra',
        'fr' => 'French',
        'fur' => 'Friulian',
        'ff' => 'Fulah',
        'gaa' => 'Ga',
        'gag' => 'Gagauz',
        'gl' => 'Galician',
        'gan' => 'Gan Chinese',
        'lg' => 'Ganda',
        'gay' => 'Gayo',
        'gba' => 'Gbaya',
        'gez' => 'Geez',
        'ka' => 'Georgian',
        'de' => 'German',
        'aln' => 'Gheg Albanian',
        'bbj' => 'Ghomala',
        'glk' => 'Gilaki',
        'gil' => 'Gilbertese',
        'gom' => 'Goan Konkani',
        'gon' => 'Gondi',
        'gor' => 'Gorontalo',
        'got' => 'Gothic',
        'grb' => 'Grebo',
        'el' => 'Greek',
        'gn' => 'Guarani',
        'gu' => 'Gujarati',
        'guz' => 'Gusii',
        'gwi' => 'Gwichʼin',
        'hai' => 'Haida',
        'ht' => 'Haitian',
        'hak' => 'Hakka Chinese',
        'ha' => 'Hausa',
        'haw' => 'Hawaiian',
        'he' => 'Hebrew',
        'hz' => 'Herero',
        'hil' => 'Hiligaynon',
        'hi' => 'Hindi',
        'ho' => 'Hiri Motu',
        'hit' => 'Hittite',
        'hmn' => 'Hmong',
        'hu' => 'Hungarian',
        'hup' => 'Hupa',
        'iba' => 'Iban',
        'ibb' => 'Ibibio',
        'is' => 'Icelandic',
        'io' => 'Ido',
        'ig' => 'Igbo',
        'ilo' => 'Iloko',
        'smn' => 'Inari Sami',
        'id' => 'Indonesian',
        'izh' => 'Ingrian',
        'inh' => 'Ingush',
        'ia' => 'Interlingua',
        'ie' => 'Interlingue',
        'iu' => 'Inuktitut',
        'ik' => 'Inupiaq',
        'ga' => 'Irish',
        'it' => 'Italian',
        'jam' => 'Jamaican Creole English',
        'ja' => 'Japanese',
        'jv' => 'Javanese',
        'kaj' => 'Jju',
        'dyo' => 'Jola-Fonyi',
        'jrb' => 'Judeo-Arabic',
        'jpr' => 'Judeo-Persian',
        'jut' => 'Jutish',
        'kbd' => 'Kabardian',
        'kea' => 'Kabuverdianu',
        'kab' => 'Kabyle',
        'kac' => 'Kachin',
        'kgp' => 'Kaingang',
        'kkj' => 'Kako',
        'kl' => 'Kalaallisut',
        'kln' => 'Kalenjin',
        'xal' => 'Kalmyk',
        'kam' => 'Kamba',
        'kbl' => 'Kanembu',
        'kn' => 'Kannada',
        'kr' => 'Kanuri',
        'kaa' => 'Kara-Kalpak',
        'krc' => 'Karachay-Balkar',
        'krl' => 'Karelian',
        'ks' => 'Kashmiri',
        'csb' => 'Kashubian',
        'kaw' => 'Kawi',
        'kk' => 'Kazakh',
        'ken' => 'Kenyang',
        'kha' => 'Khasi',
        'km' => 'Khmer',
        'kho' => 'Khotanese',
        'khw' => 'Khowar',
        'ki' => 'Kikuyu',
        'kmb' => 'Kimbundu',
        'krj' => 'Kinaray-a',
        'rw' => 'Kinyarwanda',
        'kiu' => 'Kirmanjki',
        'tlh' => 'Klingon',
        'bkm' => 'Kom',
        'kv' => 'Komi',
        'koi' => 'Komi-Permyak',
        'kg' => 'Kongo',
        'kok' => 'Konkani',
        'ko' => 'Korean',
        'kfo' => 'Koro',
        'kos' => 'Kosraean',
        'avk' => 'Kotava',
        'khq' => 'Koyra Chiini',
        'ses' => 'Koyraboro Senni',
        'kpe' => 'Kpelle',
        'kri' => 'Krio',
        'kj' => 'Kuanyama',
        'kum' => 'Kumyk',
        'ku' => 'Kurdish',
        'kru' => 'Kurukh',
        'kut' => 'Kutenai',
        'nmg' => 'Kwasio',
        'ky' => 'Kyrgyz',
        'quc' => 'Kʼicheʼ',
        'lad' => 'Ladino',
        'lah' => 'Lahnda',
        'lkt' => 'Lakota',
        'lam' => 'Lamba',
        'lag' => 'Langi',
        'lo' => 'Lao',
        'ltg' => 'Latgalian',
        'la' => 'Latin',
        'es_419' => 'Latin American Spanish',
        'lv' => 'Latvian',
        'lzz' => 'Laz',
        'lez' => 'Lezghian',
        'lij' => 'Ligurian',
        'li' => 'Limburgish',
        'ln' => 'Lingala',
        'lfn' => 'Lingua Franca Nova',
        'lzh' => 'Literary Chinese',
        'lt' => 'Lithuanian',
        'liv' => 'Livonian',
        'jbo' => 'Lojban',
        'lmo' => 'Lombard',
        'nds' => 'Low German',
        'sli' => 'Lower Silesian',
        'dsb' => 'Lower Sorbian',
        'loz' => 'Lozi',
        'lu' => 'Luba-Katanga',
        'lua' => 'Luba-Lulua',
        'lui' => 'Luiseno',
        'smj' => 'Lule Sami',
        'lun' => 'Lunda',
        'luo' => 'Luo',
        'lb' => 'Luxembourgish',
        'luy' => 'Luyia',
        'mde' => 'Maba',
        'mk' => 'Macedonian',
        'jmc' => 'Machame',
        'mad' => 'Madurese',
        'maf' => 'Mafa',
        'mag' => 'Magahi',
        'vmf' => 'Main-Franconian',
        'mai' => 'Maithili',
        'mak' => 'Makasar',
        'mgh' => 'Makhuwa-Meetto',
        'kde' => 'Makonde',
        'mg' => 'Malagasy',
        'ms' => 'Malay',
        'ml' => 'Malayalam',
        'mt' => 'Maltese',
        'mnc' => 'Manchu',
        'mdr' => 'Mandar',
        'man' => 'Mandingo',
        'mni' => 'Manipuri',
        'gv' => 'Manx',
        'mi' => 'Maori',
        'arn' => 'Mapuche',
        'mr' => 'Marathi',
        'chm' => 'Mari',
        'mh' => 'Marshallese',
        'mwr' => 'Marwari',
        'mas' => 'Masai',
        'mzn' => 'Mazanderani',
        'byv' => 'Medumba',
        'men' => 'Mende',
        'mwv' => 'Mentawai',
        'mer' => 'Meru',
        'mgo' => 'Metaʼ',
        'es_MX' => 'Mexican Spanish',
        'mic' => 'Micmac',
        'dum' => 'Middle Dutch',
        'enm' => 'Middle English',
        'frm' => 'Middle French',
        'gmh' => 'Middle High German',
        'mga' => 'Middle Irish',
        'nan' => 'Min Nan Chinese',
        'min' => 'Minangkabau',
        'xmf' => 'Mingrelian',
        'mwl' => 'Mirandese',
        'lus' => 'Mizo',
        'ar_001' => 'Modern Standard Arabic',
        'moh' => 'Mohawk',
        'mdf' => 'Moksha',
        'ro_MD' => 'Moldavian',
        'lol' => 'Mongo',
        'mn' => 'Mongolian',
        'mfe' => 'Morisyen',
        'ary' => 'Moroccan Arabic',
        'mos' => 'Mossi',
        'mul' => 'Multiple Languages',
        'mua' => 'Mundang',
        'ttt' => 'Muslim Tat',
        'mye' => 'Myene',
        'naq' => 'Nama',
        'na' => 'Nauru',
        'nv' => 'Navajo',
        'ng' => 'Ndonga',
        'nap' => 'Neapolitan',
        'ne' => 'Nepali',
        'new' => 'Newari',
        'sba' => 'Ngambay',
        'nnh' => 'Ngiemboon',
        'jgo' => 'Ngomba',
        'yrl' => 'Nheengatu',
        'nia' => 'Nias',
        'niu' => 'Niuean',
        'zxx' => 'No linguistic content',
        'nog' => 'Nogai',
        'nd' => 'North Ndebele',
        'frr' => 'Northern Frisian',
        'se' => 'Northern Sami',
        'nso' => 'Northern Sotho',
        'no' => 'Norwegian',
        'nb' => 'Norwegian Bokmål',
        'nn' => 'Norwegian Nynorsk',
        'nov' => 'Novial',
        'nus' => 'Nuer',
        'nym' => 'Nyamwezi',
        'ny' => 'Nyanja',
        'nyn' => 'Nyankole',
        'tog' => 'Nyasa Tonga',
        'nyo' => 'Nyoro',
        'nzi' => 'Nzima',
        'nqo' => 'NʼKo',
        'oc' => 'Occitan',
        'oj' => 'Ojibwa',
        'ang' => 'Old English',
        'fro' => 'Old French',
        'goh' => 'Old High German',
        'sga' => 'Old Irish',
        'non' => 'Old Norse',
        'peo' => 'Old Persian',
        'pro' => 'Old Provençal',
        'or' => 'Oriya',
        'om' => 'Oromo',
        'osa' => 'Osage',
        'os' => 'Ossetic',
        'ota' => 'Ottoman Turkish',
        'pal' => 'Pahlavi',
        'pfl' => 'Palatine German',
        'pau' => 'Palauan',
        'pi' => 'Pali',
        'pam' => 'Pampanga',
        'pag' => 'Pangasinan',
        'pap' => 'Papiamento',
        'ps' => 'Pashto',
        'pdc' => 'Pennsylvania German',
        'fa' => 'Persian',
        'phn' => 'Phoenician',
        'pcd' => 'Picard',
        'pms' => 'Piedmontese',
        'pdt' => 'Plautdietsch',
        'pon' => 'Pohnpeian',
        'pl' => 'Polish',
        'pnt' => 'Pontic',
        'pt' => 'Portuguese',
        'prg' => 'Prussian',
        'pa' => 'Punjabi',
        'qu' => 'Quechua',
        'raj' => 'Rajasthani',
        'rap' => 'Rapanui',
        'rar' => 'Rarotongan',
        'rif' => 'Riffian',
        'rgn' => 'Romagnol',
        'ro' => 'Romanian',
        'rm' => 'Romansh',
        'rom' => 'Romany',
        'rof' => 'Rombo',
        'root' => 'Root',
        'rtm' => 'Rotuman',
        'rug' => 'Roviana',
        'rn' => 'Rundi',
        'ru' => 'Russian',
        'rue' => 'Rusyn',
        'rwk' => 'Rwa',
        'ssy' => 'Saho',
        'sah' => 'Sakha',
        'sam' => 'Samaritan Aramaic',
        'saq' => 'Samburu',
        'sm' => 'Samoan',
        'sgs' => 'Samogitian',
        'sad' => 'Sandawe',
        'sg' => 'Sango',
        'sbp' => 'Sangu',
        'sa' => 'Sanskrit',
        'sat' => 'Santali',
        'sc' => 'Sardinian',
        'sas' => 'Sasak',
        'sdc' => 'Sassarese Sardinian',
        'stq' => 'Saterland Frisian',
        'saz' => 'Saurashtra',
        'sco' => 'Scots',
        'gd' => 'Scottish Gaelic',
        'sly' => 'Selayar',
        'sel' => 'Selkup',
        'seh' => 'Sena',
        'see' => 'Seneca',
        'sr' => 'Serbian',
        'sh' => 'Serbo-Croatian',
        'srr' => 'Serer',
        'sei' => 'Seri',
        'ksb' => 'Shambala',
        'shn' => 'Shan',
        'sn' => 'Shona',
        'ii' => 'Sichuan Yi',
        'scn' => 'Sicilian',
        'sid' => 'Sidamo',
        'bla' => 'Siksika',
        'szl' => 'Silesian',
        'zh_Hans' => 'Simplified Chinese',
        'sd' => 'Sindhi',
        'si' => 'Sinhala',
        'sms' => 'Skolt Sami',
        'den' => 'Slave',
        'sk' => 'Slovak',
        'sl' => 'Slovenian',
        'xog' => 'Soga',
        'sog' => 'Sogdien',
        'so' => 'Somali',
        'snk' => 'Soninke',
        'azb' => 'South Azerbaijani',
        'nr' => 'South Ndebele',
        'alt' => 'Southern Altai',
        'sma' => 'Southern Sami',
        'st' => 'Southern Sotho',
        'es' => 'Spanish',
        'srn' => 'Sranan Tongo',
        'zgh' => 'Standard Moroccan Tamazight',
        'suk' => 'Sukuma',
        'sux' => 'Sumerian',
        'su' => 'Sundanese',
        'sus' => 'Susu',
        'sw' => 'Swahili',
        'ss' => 'Swati',
        'sv' => 'Swedish',
        'fr_CH' => 'Swiss French',
        'gsw' => 'Swiss German',
        'de_CH' => 'Swiss High German',
        'syr' => 'Syriac',
        'shi' => 'Tachelhit',
        'tl' => 'Tagalog',
        'ty' => 'Tahitian',
        'dav' => 'Taita',
        'tg' => 'Tajik',
        'tly' => 'Talysh',
        'tmh' => 'Tamashek',
        'ta' => 'Tamil',
        'trv' => 'Taroko',
        'twq' => 'Tasawaq',
        'tt' => 'Tatar',
        'te' => 'Telugu',
        'ter' => 'Tereno',
        'teo' => 'Teso',
        'tet' => 'Tetum',
        'th' => 'Thai',
        'bo' => 'Tibetan',
        'tig' => 'Tigre',
        'ti' => 'Tigrinya',
        'tem' => 'Timne',
        'tiv' => 'Tiv',
        'tli' => 'Tlingit',
        'tpi' => 'Tok Pisin',
        'tkl' => 'Tokelau',
        'to' => 'Tongan',
        'fit' => 'Tornedalen Finnish',
        'zh_Hant' => 'Traditional Chinese',
        'tkr' => 'Tsakhur',
        'tsd' => 'Tsakonian',
        'tsi' => 'Tsimshian',
        'ts' => 'Tsonga',
        'tn' => 'Tswana',
        'tcy' => 'Tulu',
        'tum' => 'Tumbuka',
        'aeb' => 'Tunisian Arabic',
        'tr' => 'Turkish',
        'tk' => 'Turkmen',
        'tru' => 'Turoyo',
        'tvl' => 'Tuvalu',
        'tyv' => 'Tuvinian',
        'tw' => 'Twi',
        'kcg' => 'Tyap',
        'udm' => 'Udmurt',
        'uga' => 'Ugaritic',
        'uk' => 'Ukrainian',
        'umb' => 'Umbundu',
        'und' => 'Unknown Language',
        'hsb' => 'Upper Sorbian',
        'ur' => 'Urdu',
        'ug' => 'Uyghur',
        'uz' => 'Uzbek',
        'vai' => 'Vai',
        've' => 'Venda',
        'vec' => 'Venetian',
        'vep' => 'Veps',
        'vi' => 'Vietnamese',
        'vo' => 'Volapük',
        'vro' => 'Võro',
        'vot' => 'Votic',
        'vun' => 'Vunjo',
        'wa' => 'Walloon',
        'wae' => 'Walser',
        'war' => 'Waray',
        'wbp' => 'Warlpiri',
        'was' => 'Washo',
        'guc' => 'Wayuu',
        'cy' => 'Welsh',
        'vls' => 'West Flemish',
        'fy' => 'Western Frisian',
        'mrj' => 'Western Mari',
        'wal' => 'Wolaytta',
        'wo' => 'Wolof',
        'wuu' => 'Wu Chinese',
        'xh' => 'Xhosa',
        'hsn' => 'Xiang Chinese',
        'yav' => 'Yangben',
        'yao' => 'Yao',
        'yap' => 'Yapese',
        'ybb' => 'Yemba',
        'yi' => 'Yiddish',
        'yo' => 'Yoruba',
        'zap' => 'Zapotec',
        'dje' => 'Zarma',
        'zza' => 'Zaza',
        'zea' => 'Zeelandic',
        'zen' => 'Zenaga',
        'za' => 'Zhuang',
        'gbz' => 'Zoroastrian Dari',
        'zu' => 'Zulu',
        'zun' => 'Zuni'
    );

    public $_data_genders = array(
        'male' => 'Male',
        'female' => 'Female'
    );

    public $_data_continets = array(
        'africa' => 'Africa',
        'antarctica' => 'Antarctica',
        'asia' => 'Asia',
        'australia' => 'Australia',
        'europe' => 'Europe',
        'north-america' => 'North America',
        'south-america' => 'South America'
    );

    public $_data_months = array(
        '01' => 'January',
        '02' => 'February',
        '03' => 'March',
        '04' => 'April',
        '05' => 'May',
        '06' => 'June',
        '07' => 'July',
        '08' => 'August',
        '09' => 'September',
        '10' => 'October',
        '11' => 'November',
        '12' => 'December'
    );

    public $_data_daysweek = array(
        'sunday' => 'Sunday',
        'monday' => 'Monday',
        'tuesday' => 'Tuesday',
        'wednesday' => 'Wednesday',
        'thursday' => 'Thursday',
        'friday' => 'Friday',
        'saturday' => 'Saturday'
    );

    public $_data_clothing_sizes = array(
        'XXS' => 'XXS',
        'XS' => 'XS',
        'S' => 'S',
        'M' => 'M',
        'L' => 'L',
        'XL' => 'XL',
        'XXL' => 'XXL',
        '3XL' => '3XL',
        '4XL' => '4XL',
        '5XL' => '5XL',
        '6XL' => '6XL',
        '7XL' => '7XL'
    );

    public $_data_marital_status = array(
        'single' => 'Single',
        'married' => 'Married',
        'divorced' => 'Divorced',
        'widowed' => 'Widowed'
    );

    public $mask = array(
        'percent' => '099%',
        'mysql_datetime' => '0000-00-00 00:00:00',
        'phone_us' => '(000) 000-0000',
        'phone_int' => '+000 00 000 0000',
        'ipv4' => '099.099.099.099',
        'credit_card' => '0000 0000 0000 0000',
        'ssn_us' => '000-00-0000'
    );

    public $regex = array(
        'slug' => '^[a-z0-9]*[a-z0-9\-\_]*[a-z0-9]*$',
        'integer' => '^[-+]?\d*$',
        'positive_integer' => '^[+]?\d*$',
        'float' => '^[-+]?\d*\.?\d*$',
        'positive_float' => '^[+]?\d*\.?\d*$',
        'letters_only' => '^[A-Za-z]*$',
        'alphanumerics' => '^[0-9A-Za-z]*$',
        'hex_number' => '^[a-f0-9]*$',
        'hex_color' => '^#?([a-fA-F0-9]{6}|[a-fA-F0-9]{3})$',
        'asin' => '^(B[0-9]{2}[a-zA-Z0-9]{7}|[0-9]{9}(X|[0-9]))$',
        'isbn' => '^(\d{1,3}([- ])\d{1,5}\2\d{1,7}\2\d{1,6}\2(\d|X))|(\d{1,5}([- ])\d{1,7}\5\d{1,6}\5(\d|X))|(\d{13})|(\d{10})$'
    );

    public function __construct() {
        add_filter('gdcet_meta_text_restriction_methods_mask', array($this, '_mask'));
        add_filter('gdcet_meta_text_restriction_methods_regex', array($this, '_regex'));
        add_filter('gdcet_meta_text_restriction_methods_regex_title', array($this, '_regex_title'), 10, 2);
        add_filter('gdcet_meta_select_predefined_lists', array($this, '_list'));
        add_filter('gdcet_meta_select_remote_sources', array($this, '_remote'));
    }

    public function _remote() {
        $list['gdcet_meta_predefined_data::remote_continets'] = __("Default", "gd-content-tools").': '.__("Continets", "gd-content-tools");
        $list['gdcet_meta_predefined_data::remote_countries'] = __("Default", "gd-content-tools").': '.__("Countries", "gd-content-tools");
        $list['gdcet_meta_predefined_data::remote_us_states'] = __("Default", "gd-content-tools").': '.__("US States", "gd-content-tools");
        $list['gdcet_meta_predefined_data::remote_canada_states'] = __("Default", "gd-content-tools").': '.__("Canadian States", "gd-content-tools");
        $list['gdcet_meta_predefined_data::remote_languages'] = __("Default", "gd-content-tools").': '.__("Languages", "gd-content-tools");

        return $list;
    }

    public function _list($list) {
        $list['gdcet_meta_predefined_data::list_genders'] = __("Default", "gd-content-tools").': '.__("Genders", "gd-content-tools");
        $list['gdcet_meta_predefined_data::list_months'] = __("Default", "gd-content-tools").': '.__("Months", "gd-content-tools");
        $list['gdcet_meta_predefined_data::list_daysweek'] = __("Default", "gd-content-tools").': '.__("Days of the Week", "gd-content-tools");
        $list['gdcet_meta_predefined_data::list_clothing_sizes'] = __("Default", "gd-content-tools").': '.__("Clothing Sizes", "gd-content-tools");
        $list['gdcet_meta_predefined_data::list_marital_status'] = __("Default", "gd-content-tools").': '.__("Marital Status", "gd-content-tools");

        $list['gdcet_meta_predefined_data::list_continets'] = __("Default", "gd-content-tools").': '.__("Continets", "gd-content-tools");
        $list['gdcet_meta_predefined_data::list_countries'] = __("Default", "gd-content-tools").': '.__("Countries", "gd-content-tools");
        $list['gdcet_meta_predefined_data::list_us_states'] = __("Default", "gd-content-tools").': '.__("US States", "gd-content-tools");
        $list['gdcet_meta_predefined_data::list_canada_states'] = __("Default", "gd-content-tools").': '.__("Canadian States", "gd-content-tools");
        $list['gdcet_meta_predefined_data::list_languages'] = __("Default", "gd-content-tools").': '.__("Languages", "gd-content-tools");

        $list['gdcet_meta_predefined_data::list_wordpress_major'] = __("WordPress", "gd-content-tools").': '.__("Major Versions", "gd-content-tools");
        $list['gdcet_meta_predefined_data::list_wordpress_minor'] = __("WordPress", "gd-content-tools").': '.__("All Versions", "gd-content-tools");

        $list['gdcet_meta_predefined_data::list_php_major'] = __("PHP", "gd-content-tools").': '.__("Major Versions", "gd-content-tools");

        return $list;
    }

    public function _mask($list) {
        $list['mask|gdcet_meta_predefined_data::mask_percent'] = __("Default", "gd-content-tools").': '.__("Percent", "gd-content-tools");
        $list['mask|gdcet_meta_predefined_data::mask_mysql_datetime'] = __("Default", "gd-content-tools").': '.__("MySQL DateTime", "gd-content-tools");
        $list['mask|gdcet_meta_predefined_data::mask_phone_us'] = __("Default", "gd-content-tools").': '.__("Phone Number US", "gd-content-tools");
        $list['mask|gdcet_meta_predefined_data::mask_phone_int'] = __("Default", "gd-content-tools").': '.__("Phone Number International", "gd-content-tools");
        $list['mask|gdcet_meta_predefined_data::mask_ipv4'] = __("Default", "gd-content-tools").': '.__("IP v4", "gd-content-tools");
        $list['mask|gdcet_meta_predefined_data::mask_credit_card'] = __("Default", "gd-content-tools").': '.__("Credit Card", "gd-content-tools");
        $list['mask|gdcet_meta_predefined_data::mask_ssn_us'] = __("Default", "gd-content-tools").': '.__("SSN", "gd-content-tools");

        return $list;
    }

    public function _regex($list) {
        $list['regex|gdcet_meta_predefined_data::regex_slug'] = __("Default", "gd-content-tools").': '.__("Slug", "gd-content-tools");
        $list['regex|gdcet_meta_predefined_data::regex_integer'] = __("Default", "gd-content-tools").': '.__("Integer", "gd-content-tools");
        $list['regex|gdcet_meta_predefined_data::regex_positive_integer'] = __("Default", "gd-content-tools").': '.__("Positive Integer", "gd-content-tools");
        $list['regex|gdcet_meta_predefined_data::regex_float'] = __("Default", "gd-content-tools").': '.__("Float", "gd-content-tools");
        $list['regex|gdcet_meta_predefined_data::regex_positive_float'] = __("Default", "gd-content-tools").': '.__("Positive Float", "gd-content-tools");
        $list['regex|gdcet_meta_predefined_data::regex_letters_only'] = __("Default", "gd-content-tools").': '.__("Letters", "gd-content-tools");
        $list['regex|gdcet_meta_predefined_data::regex_alphanumerics'] = __("Default", "gd-content-tools").': '.__("Alphanumeric", "gd-content-tools");
        $list['regex|gdcet_meta_predefined_data::regex_hex_number'] = __("Default", "gd-content-tools").': '.__("Hex Number", "gd-content-tools");
        $list['regex|gdcet_meta_predefined_data::regex_hex_color'] = __("Default", "gd-content-tools").': '.__("Hex Color", "gd-content-tools");
        $list['regex|gdcet_meta_predefined_data::regex_asin'] = __("Default", "gd-content-tools").': '.__("Amazon ASIN", "gd-content-tools");
        $list['regex|gdcet_meta_predefined_data::regex_isbn'] = __("Default", "gd-content-tools").': '.__("ISBN 10/13", "gd-content-tools");

        return $list;
    }

    public function _regex_title($title, $name) {
        $list = array(
            'slug' => __("Alphanumeric characters, underscores and dashes.", "gd-content-tools"),
            'integer' => __("Integer number.", "gd-content-tools"),
            'positive_integer' => __("Positive integer number.", "gd-content-tools"),
            'float' => __("Any number.", "gd-content-tools"),
            'positive_float' => __("Any positive number.", "gd-content-tools"),
            'letters_only' => __("Alphabet letters.", "gd-content-tools"),
            'alphanumerics' => __("Alphanumeric characters.", "gd-content-tools"),
            'hex_number' => __("Hexadecimal numbers.", "gd-content-tools"),
            'hex_color' => __("Hexadecimal Color", "gd-content-tools"),
            'asin' => __("Amazon ASIN code.", "gd-content-tools"),
            'isbn' => __("ISBN 10/13 code (with or without dashes).", "gd-content-tools")
        );

        $key = array_search($name, $this->regex);

        if ($key !== false) {
            return $list[$key];
        }

        return $title;
    }

    public static function plain_to_associated($list) {
        $new = array();

        foreach ($list as $value) {
            $new[$value] = $value;
        }

        return $new;
    }

    public static function __callStatic($name, $arguments) {
        $parts = explode('_', $name, 2);

        $method = $parts[0];
        $source = $parts[1];

        if ($method == 'list' || $method == 'remote') {
            $filter = 'gdcet_data_list_'.$source;
            $property = '_data_'.$source;

            $data = array();
            if (isset(gdcet_predefined_data_meta()->{$property})) {
                $data = gdcet_predefined_data_meta()->{$property};
            }

            $data = apply_filters($filter, $data);
            $input = in_array($source, gdcet_predefined_data_meta()->_numeric_arrays) ? gdcet_predefined_data_meta()->plain_to_associated($data) : $data;

            if ($method == 'list') {
                return $input;
            } else if ($method == 'remote') {
                $search = isset($arguments[0]) ? $arguments[0] : false;

                if ($search === false) {
                    return array();
                }

                if (is_array($search)) {
                    $output = array();

                    foreach ($search as $key) {
                        if (isset($input[$key])) {
                            $output[$key] = $input[$key];
                        }
                    }

                    return $output;
                } else if (is_string($search) || is_numeric($search)) {
                    $page = isset($arguments[1]) ? $arguments[1] : 1;
                    $pager = isset($arguments[2]) ? $arguments[2] : 25;
                    $page = $page > 1 ? $page - 1 : 0;

                    $filtered = array_filter($input, function($val, $key) use ($search) {
                        return strpos($val, $search) !== false || strpos($key, $search) !== false;
                    }, ARRAY_FILTER_USE_BOTH);

                    return array(
                        'total_count' => count($filtered),
                        'filtered' => array_slice($filtered, $page * $pager, $pager)
                    );
                }
            }
        } else if ($method == 'regex') {
            if (isset(gdcet_predefined_data_meta()->regex[$source])) {
                return gdcet_predefined_data_meta()->regex[$source];
            } else {
                return '';
            }
        } else if ($method == 'mask') {
            if (isset(gdcet_predefined_data_meta()->mask[$source])) {
                return gdcet_predefined_data_meta()->mask[$source];
            } else {
                return '';
            }
        }
    }
}

global $_gdcet_meta_predefined_data;

$_gdcet_meta_predefined_data = new gdcet_meta_predefined_data();

function gdcet_predefined_data_meta() {
    global $_gdcet_meta_predefined_data;
    return $_gdcet_meta_predefined_data;
}
